/**@typedef {import("../column.js").ColumnTypes} Column*/

const TSQLTypes = {
    /**@returns {Column}*/ varChar: (length) => ({ type: "VARCHAR", length }),
    /**@returns {Column}*/ nVarChar: (length) => ({ type: "NVARCHAR", length }),
    /**@returns {Column}*/ text: () => ({ type: "TEXT" }),
    /**@returns {Column}*/ int: () => ({ type: "INT" }),
    /**@returns {Column}*/ bigInt: () => ({ type: "BIGINT" }),
    /**@returns {Column}*/ tinyInt: () => ({ type: "TINYINT" }),
    /**@returns {Column}*/ smallInt: () => ({ type: "SMALLINT" }),
    /**@returns {Column}*/ bit: () => ({ type: "BIT" }),
    /**@returns {Column}*/ float: () => ({ type: "FLOAT" }),
    /**@returns {Column}*/ numeric: (precision, scale) => ({ type: "NUMERIC", precision, scale }),
    /**@returns {Column}*/ decimal: (precision, scale) => ({ type: "DECIMAL", precision, scale }),
    /**@returns {Column}*/ real: () => ({ type: "REAL" }),
    /**@returns {Column}*/ date: () => ({ type: "DATE" }),
    /**@returns {Column}*/ dateTime: () => ({ type: "DATETIME" }),
    /**@returns {Column}*/ dateTime2: (scale) => ({ type: "DATETIME2", scale }),
    /**@returns {Column}*/ dateTimeOffset: (scale) => ({ type: "DATETIMEOFFSET", scale }),
    /**@returns {Column}*/ smallDateTime: () => ({ type: "SMALLDATETIME" }),
    /**@returns {Column}*/ time: (scale) => ({ type: "TIME", scale }),
    /**@returns {Column}*/ uniqueIdentifier: () => ({ type: "UNIQUEIDENTIFIER" }),
    /**@returns {Column}*/ smallMoney: () => ({ type: "SMALLMONEY" }),
    /**@returns {Column}*/ money: () => ({ type: "MONEY" }),
    /**@returns {Column}*/ binary: (length) => ({ type: "BINARY", length }),
    /**@returns {Column}*/ varBinary: (length) => ({ type: "VARBINARY", length }),
    /**@returns {Column}*/ image: () => ({ type: "IMAGE" }),
    /**@returns {Column}*/ xml: () => ({ type: "XML" }),
    /**@returns {Column}*/ char: (length) => ({ type: "CHAR", length }),
    /**@returns {Column}*/ nChar: (length) => ({ type: "NCHAR", length }),
    /**@returns {Column}*/ nText: () => ({ type: "NTEXT" }),
    /**@returns {Column}*/ tvp: (tvpType) => ({ type: "TVP", tvpType }),
    /**@returns {Column}*/ udt: () => ({ type: "UDT" }),
    /**@returns {Column}*/ geography: () => ({ type: "GEOGRAPHY" }),
    /**@returns {Column}*/ geometry: () => ({ type: "GEOMETRY" }),
    /**@returns {Column}*/ variant: () => ({ type: "VARIANT" }),
};
module.exports = TSQLTypes;
